server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/portfolioDb
  jpa:
    hibernate:
      ddl-auto: create


